Revert "services: add pid cleanup and pid file petting"
This reverts commit beb99c9e081c0670f01b1a5f08db82f593f768c7.

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -56,6 +56,9 @@ if [ -f "\$pid_fn" ] && kill -0 \$(cat \$pid_fn) 2>/dev/null; then
 fi
 echo \$BASHPID > \$pid_fn
 
+# cleanup on exit
+trap "rm \$pid_fn" INT TERM EXIT
+
 rm -f ${BASEDIR}/var/log/${service}/lock
 ${BASEDIR}/bin/rotate ${BASEDIR}/var/exit/${service}/exit_code
 export TULS_BASEDIR=${BASEDIR}
@@ -68,7 +71,7 @@ export TULS_PATH=${BASEDIR}/3rdparty/busybox/bin/:${BASEDIR}/3rdparty/busybox/sb
   # write exit code
   echo \$? > ${BASEDIR}/var/exit/${service}/exit_code
 } | ${BASEDIR}/3rdparty/busybox/usr/sbin/svlogd -tt ${BASEDIR}/var/log/${service}/
-rm \$pid_fn
+
 EOI
     chmod +x ${BASEDIR}/var/lib/${service}
     chmod +x ${BASEDIR}/var/lib/${service}_child
